name: ds
description: "Application design system."
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.6.2"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  shared_dependencies:
  core_common:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.app.ds
    iosBundleIdentifier: com.app.ds
