name: shared_dependencies
description: "A new Flutter package project."
version: 0.0.1

publish_to:  none

environment:
  sdk: ">=3.6.2"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^4.1.0
  firebase_crashlytics: ^5.0.1

  ds:

  get_it: ^8.2.0
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  go_router: ^16.2.1
  flutter_localization: ^0.3.3
  intl: ^0.20.2
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.8.0
  json_serializable: ^6.11.1

flutter:
